# -*- coding: utf-8 -*-
"""CriandoUmaAPIComFlaskNoAmbienteCOLAB.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fYfhQZGyrZyOc2DJ7i_T5JcAAR6yoklG
"""

# !pip install flask
# !pip install pyngrok

ngrok_key = "2ei0zdrFR54PLqWy8UT6Z15J50O_6ZkqnB7iSPWU4gksb2rNH"
port = 5000

from pyngrok import ngrok
from flask import (
    request,
    Flask
)

ngrok.set_auth_token(ngrok_key)
url = ngrok.connect(port).public_url

app = Flask(__name__)

data_base = {
  1: {
      'name': 'Mahesh',
      'age': 25,
      'city': 'Bangalore',
      'country': 'India'
  },
  2: {
      'name': 'Alex',
      'age': 26,
      'city': 'London',
      'country': 'UK'
  },
  3: {
      'name': 'David',
      'age': 27,
      'city': 'San Francisco',
      'country': 'USA'
  },
  4: {
      'name': 'Jhon',
      'age': 28,
      'city': 'Toronto',
      'country': 'Canada'
  },
  5: {
      'name': 'Chris',
      'age': 29,
      'city': 'Paris',
      'country': 'France'
  },
  6: {
      'name': 'Thiago',
      'age': 28,
      'city': 'Queimados',
      'country': 'Brazil'
  }
}

def generate_html_with_names() -> str:
  global data_base
  global url
  html_string = ""
  for id in data_base:
    html_string += f'<li><a href={url}/{id}>{data_base[id]["name"]}</a></li>'

  return html_string

@app.route('/<int:id>')
def open_record(id):
  global data_base
  return (
      f"<html>"
        f"<header>"
          f"<h1 align='center'>Visualize Record</h1>"
        f"</header>"
        f"<body>"
          f"<table>"
            f"<tr>"
              f"<td align='left'>"
                f"<p>Record id:</p>"
              f"</td>"
              f"<td align='right'>"
                f"<p>{id:04d}</p>"
              f"</td>"
            f"</tr>"
            f"<tr>"
              f"<td align='left'>"
                f"<p>Name:</p>"
              f"</td>"
              f"<td align='right'>"
                f"<p>{data_base[id]['name']}</p>"
              f"</td>"
            f"</tr>"
            f"<tr>"
              f"<td align='left'>"
                f"<p>Age:</p>"
              f"</td>"
              f"<td align='right'>"
                f"<p>{data_base[id]['age']}</p>"
              f"</td>"
            f"</tr>"
            f"<tr>"
              f"<td align='left'>"
                f"<p>City/Country:</p>"
              f"</td>"
              f"<td align='right'>"
                f"<p>{data_base[id]['city']}/{data_base[id]['country']}</p>"
              f"</td>"
            f"</tr>"
          f"</table>"
          f"<a href={url}/>Back</a>"
        f"</body:"
      f"</html>"
  )

@app.route("/")
def home():
  return (
      f"<html>"
        f"<header>"
          f"<h1 align='center'>DIO's Challenge #5</h1>"
        f"</header>"
        f"<body>"
          f"<h2 align='center'>Welcome!!</h2>"
          f"<h3>Choose a record:</h3>"
          f"{generate_html_with_names()}"
        f"</body>"
      f"</html>")

print(url)

app.run(port = port)